version: "3"

services:
  app:
    build: .
    container_name: collect-points-api
    ports:
      - 3333:3333
    depends_on:
      - mysql
    volumes:
      - .:/home/node/code

  mysql:
    image: mysql:5
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./docker/mysql:/docker-entrypoint-initdb.d
      - .:/app
    environment:
      - MYSQL_DATABASE=collect_points
      - MYSQL_ROOT_PASSWORD=root
